wand:
  material: BLAZE_ROD
  custom-model-data: 777001
  itemsadder-id: ""   # optional e.g. galaxy:lunar_wand
  name: "§d☾ Lunár Kígyó Pálca"
  lore:
    - "§7Sebzés: §c150"
    - "§6BAL KATTINTÁS §7– §aKígyó lövedék"
    - "§6JOBB KATTINTÁS §7– §dMimik-Klón (max 2)"
    - "§8• Nincs mana, csak cooldown"

combat:
  damage: 150.0
  headshot-multiplier: 1.8

cooldowns:
  shoot-seconds: 1.0
  clone-seconds: 2.0

clone:
  max-per-player: 2
  lifetime-seconds: 10
  target-range: 22
  shoot-interval-ticks: 10
  rotate-every-tick: true
  allow-target-players: false
  allow-target-friendly: true

projectile:
  max-distance: 35.0
  step: 0.45
  hit-radius: 0.65
  body-points: 6
  body-spacing: 0.12
  wave:
    amplitude: 0.45
    frequency: 0.65
  particle:
    type: DUST
    rgb: "80,255,120"
    size: 1.2
